name = "cloudfare-my-pages"
type = "javascript"
zone_id = ""
account_id = "17e74cdc6c52ebb606f03ee21de047b9"
route = ""
workers_dev = true
compatibility_date = "2021-10-21"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
kv_namespaces = [ 
	 { binding = "postsCollection", id = "1143caf3da3f44bc9e3fd332069b74b1" }
]

